# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    # (this is just an example, not intended to be a production configuration)
