CREATE DATABASE SA;

CREATE TABLE CLIENT(
    ID integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) UNIQUE
);

CREATE TABLE sentiment(
ID integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
TEXTE VARCHAR(50),
TYPE VARCHAR(10),
CLIENT_ID integer,
CONSTRAINT client_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);